### ISSUE TITLE
More info

### ISSUE THREAD

**Issue by JFOC** [PTNUSASATUINTIARTHA-DOKU/WHMCS-DOKU#1]
Hello,
Need more information for each field for configuration.

Development and production. EDU. Identify. Installment.

**Comment by aryoprakarsa** [comment]
@JFOC each field for the configuration perhaps you give me more details which part and/or configuration you wanted to know.

So let me answer your question stated in your question : 
- **Development** = When your choose this in the development so you're in the development mode
- **Production** =  When you choose as the production so you're in the production
- **EDU** = EDU are Early Detection Unit where it's unit specialized for second layer fraud detection.
- **Identiy** = Allow Merchant to identified the channel that Customer chose. Merchant should inform the URL where DOKU server will send the notification message
- **Installment** = Installment are where the full amount are devided with certain month ( this thing you need to discuss with our sales team since it's relate with bank. For instance the full amount are Rp. 1,000,000 and you setup for 3 months installment on us so it will bill to your customer are Rp. 1,000,000 / 3 = 333,333 each month for 3 months period.

Plese @JFOC let me know if you need further assistance. Thanks

**Comment by JFOC** [comment]
In the DOKU dashboard, there is only one key, no development and production key differentiation ?

The installment, I cannot just use the credit card method? Need to contact your sales for credit-card activation ?

**Comment by aryoprakarsa** [comment]
@JFOC well it has differentation between development and shared key. 

Q: In the DOKU dashboard, there is only one key, no development and production key differentiation ?
A: Yes, it's only for development once you approved you will receieved production mall id and shared key

Q: The installment, I cannot just use the credit card method? Need to contact your sales for credit-card activation ?
A: Yes for installment you need to contact our sales department at sales@doku.com

Q: Chain Merchant Name, I can fill anything or need approval ?
A: For chain merchant you need to be approval by our integration team

Q: URL things, in the DOKU Dashboard there are only 3, in the whmcs module there are 4 URL (Notify, Redirect, Review, Identify) ?
A: As I previously message that review url if you're using EDU so its only available if you're using EDU

Plese @JFOC let me know if you need further assistance. Thanks
